/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./components/common/AppLayout.vue')['default']
    AppSidebar: typeof import('./components/common/AppSidebar.vue')['default']
    ConversationList: typeof import('./components/chat/ConversationList.vue')['default']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    ImageDropZone: typeof import('./components/toolbox/ImageDropZone.vue')['default']
    JsonEditor: typeof import('./components/toolbox/JsonEditor.vue')['default']
    MessageBubble: typeof import('./components/chat/MessageBubble.vue')['default']
    MessageInput: typeof import('./components/chat/MessageInput.vue')['default']
    MessageList: typeof import('./components/chat/MessageList.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDescriptions: typeof import('naive-ui')['NDescriptions']
    NDescriptionsItem: typeof import('naive-ui')['NDescriptionsItem']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NoteCard: typeof import('./components/notes/NoteCard.vue')['default']
    NPagination: typeof import('naive-ui')['NPagination']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpin: typeof import('naive-ui')['NSpin']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagInput: typeof import('./components/common/TagInput.vue')['default']
    TiptapEditor: typeof import('./components/notes/TiptapEditor.vue')['default']
    TiptapToolbar: typeof import('./components/notes/TiptapToolbar.vue')['default']
    TodoCreateModal: typeof import('./components/todos/TodoCreateModal.vue')['default']
    TodoEditModal: typeof import('./components/todos/TodoEditModal.vue')['default']
    TodoFilters: typeof import('./components/todos/TodoFilters.vue')['default']
    TodoItem: typeof import('./components/todos/TodoItem.vue')['default']
    TodoList: typeof import('./components/todos/TodoList.vue')['default']
    ToolCard: typeof import('./components/toolbox/ToolCard.vue')['default']
  }
}
